use syscxp_tunnel;

ALTER TABLE SpeedTestTunnelVO ADD CONSTRAINT fkSpeedTestTunnelVOTunnelVO FOREIGN KEY (tunnelUuid) REFERENCES TunnelEO (uuid) ON DELETE CASCADE;


##节点区域关系表

ALTER TABLE `syscxp_tunnel`.`ZoneNodeRefVO` ADD CONSTRAINT fkZoneNodeRefVONodeEO FOREIGN KEY (nodeUuid) REFERENCES NodeEO (uuid) ON DELETE CASCADE;
ALTER TABLE `syscxp_tunnel`.`ZoneNodeRefVO` ADD CONSTRAINT fkZoneNodeRefVOzoneVO FOREIGN KEY (zoneUuid) REFERENCES ZoneVO (uuid) ON DELETE CASCADE;

##云专线端口信息表
ALTER TABLE TunnelSwitchPortVO ADD CONSTRAINT fkTunnelSwitchPortVOTunnelEO FOREIGN KEY (tunnelUuid) REFERENCES TunnelEO (uuid) ON DELETE CASCADE;

##Qinq模式网段
ALTER TABLE QinqVO ADD CONSTRAINT fkQinqVOTunnelEO FOREIGN KEY (tunnelUuid) REFERENCES TunnelEO (uuid) ON DELETE CASCADE;


##通道监控
ALTER TABLE TunnelMonitorVO ADD CONSTRAINT fkTunnelMonitorVOTunnelEO FOREIGN KEY (tunnelUuid) REFERENCES TunnelEO (uuid) ON DELETE CASCADE;


ALTER TABLE MonitorHostVO ADD CONSTRAINT fkMonitorHostVOHostEO FOREIGN KEY (uuid) REFERENCES HostEO (uuid) ON UPDATE RESTRICT ON DELETE CASCADE;
ALTER TABLE MonitorHostVO ADD CONSTRAINT fkMonitorHostVONodeEO FOREIGN KEY (nodeUuid) REFERENCES NodeEO (uuid) ON UPDATE RESTRICT ON DELETE CASCADE;


ALTER TABLE SpeedRecordsVO ADD CONSTRAINT fkSpeedRecordsVOTunnelEO FOREIGN KEY (tunnelUuid) REFERENCES TunnelEO (uuid) ON DELETE CASCADE;

