#!/bin/sh

# the following is chkconfig init header
#
# syscxp-monitoragent:   syscxp monitor agent daemon
#
# chkconfig: 345 97 03
#
# processname: monitoragent
# pidfile: /var/run/syscxp/monitoragent.pid
#

check_status() {
	pidfile='/var/run/syscxp/monitoragent.pid'
	if [ ! -f $pidfile ]; then
		echo "syscxp monitor agent is stopped"
		exit 1
	else
		pid=`cat $pidfile`
		ps -p $pid > /dev/null
		if [ $? -eq 0 ]; then
			echo "syscxp monitor agent is running, pid is $pid"
			exit 0
		else
			echo "syscxp monitor agent is stopped, but pidfile at $pidfile is not cleaned. It may be caused by monitor agent crashed at last time, manually cleaning it would be ok"
			exit 1
		fi
	fi
}

if [ $# -eq 0 ]; then
	echo "usage: $0
[start|stop|restart|status]"
	exit 1
fi

if [ "$@" = "status" ]; then
	check_status
else
	. /var/lib/syscxp/virtualenv/monitor/bin/activate && python -c "from monitoragent import mdaemon; mdaemon.main()" $@
fi

if [ $? -eq 0 ]; then
    echo "$@ syscxp monitor agent .... SUCCESS"
    exit 0
else
    echo "$@ syscxp monitor agent .... FAILED"
    exit 1
fi
