//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.22 at 06:08:17 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://syscxp.com/schema/syscxp", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.syscxp.core.config;
